### ISSUE TITLE
[apple] xharness is unable to find the default installed simulators

### ISSUE THREAD

**Issue by mattleibow** [dotnet/xharness#1042]
Doing `xharness apple state` shows the sims:

```
% xharness apple state                      
[8.0.0-prerelease.23326.1+747cfb23923a644ee43b012c5bcd7b738a485b8e] XHarness command issued: apple state
Runtime Enviroment:
  Machine name:	MattOne
  OS Name:	Mac OS X
  OS Version:	10.18
  OS Platform:	Darwin

Developer Tools:
  Xcode:	14.3.1 - /Applications/Xcode.app
  Mlaunch:	Xamarin.Launcher 1.0.44 (refs/heads/main: 729eaa8fe3) - /Users/matthew/.dotnet/tools/.store/microsoft.dotnet.xharness.cli/8.0.0-prerelease.23326.1/microsoft.dotnet.xharness.cli/8.0.0-prerelease.23326.1/tools/net8.0/any/../../../runtimes/any/native/mlaunch/bin/mlaunch

Installed Simulators:
  iPhone SE (3rd generation)            iOS 16.4      iPhone SE 3rd generation
  iPhone 14                             iOS 16.4      iPhone 14
  iPhone 14 Plus                        iOS 16.4      iPhone 14 Plus
  iPhone 14 Pro                         iOS 16.4      iPhone 14 Pro
  iPhone 14 Pro Max                     iOS 16.4      iPhone 14 Pro Max
  iPad Air (5th generation)             iOS 16.4      iPad Air 5th generation
  iPad (10th generation)                iOS 16.4      iPad 10th generation
  iPad mini (6th generation)            iOS 16.4      iPad mini 6th generation
  iPad Pro (11-inch) (4th generation)   iOS 16.4      iPad Pro 11 inch 4th generation 8GB
  iPad Pro (12.9-inch) (6th generation) iOS 16.4      iPad Pro 12 9 inch 6th generation 8GB

Connected Devices:
  none
```

But a `apple simulators list --installed` shows nothing:

```
% xharness apple simulators list --installed
[8.0.0-prerelease.23326.1+747cfb23923a644ee43b012c5bcd7b738a485b8e] XHarness command issued: apple simulators list --installed
info: File '/var/folders/x1/2s1cq4312cx35w541x8d45mm0000gn/T/simulator-installer/index-14.3.1-EA3EACC9-A0BE-423D-9BA3-AA8B9FE68E38.dvtdownloadableindex' already exists, skipped download
XHarness exit code: 0
```

I am using a M1 Mac Book Pro. Ventura 13.4 and Xcode 14.3.1

**Comment by mattleibow** [comment]
When I do apple test, it also can't find it:

```
 % xharness apple test --app sample/SampleMauiApp/bin/Debug/net7.0-ios/iossimulator-arm64/SampleMauiApp.app --output-directory artifacts --target ios-simulator -v
[8.0.0-prerelease.23326.1+747cfb23923a644ee43b012c5bcd7b738a485b8e] XHarness command issued: apple test --app sample/SampleMauiApp/bin/Debug/net7.0-ios/iossimulator-arm64/SampleMauiApp.app --output-directory artifacts --target ios-simulator -v
info: Preparing run for ios-simulator
info: Looking for available ios-simulator simulators..
dbug: Looking for available ios-simulator simulators. Storing logs into list-ios-simulator-20230706_015506.log
fail: Failed to find/create suitable simulator
XHarness exit code: 81 (DEVICE_NOT_FOUND)
```

However, the logs do show it is available...
```
[01:55:10.7429220]         AvailableDevices (10):
[01:55:10.7448090]             SimDevice: iPhone SE (3rd generation) (71331215-9244-4E77-98AB-860172DC7DA1, iOS 16.4, Shutdown)
[01:55:10.7448300]                 UDID: 71331215-9244-4E77-98AB-860172DC7DA1
[01:55:10.7448710]                 SimRuntime: com.apple.CoreSimulator.SimRuntime.iOS-16-4
[01:55:10.7448750]                 DeviceType: com.apple.CoreSimulator.SimDeviceType.iPhone-SE-3rd-generation
[01:55:10.7448880]                 DeviceSet: /Users/matthew/Library/Developer/CoreSimulator/Devices
[01:55:10.7449690]                 Available: True
[01:55:10.7449740]                 Name: iPhone SE (3rd generation)
[01:55:10.7449770]                 State: Shutdown
[01:55:10.7449820]                 StateString: Shutdown
[01:55:10.7450670]                 MemoryWarningFilePath: /Users/matthew/Library/Developer/CoreSimulator/Devices/71331215-9244-4E77-98AB-860172DC7DA1/data/var/run/memory_warning_simulation
[01:55:10.7451300]                 LogPath: /Users/matthew/Library/Logs/CoreSimulator/71331215-9244-4E77-98AB-860172DC7DA1
[01:55:10.7451370]                 DataPath: /Users/matthew/Library/Developer/CoreSimulator/Devices/71331215-9244-4E77-98AB-860172DC7DA1/data
[01:55:10.7451430]                 DevicePath: /Users/matthew/Library/Developer/CoreSimulator/Devices/71331215-9244-4E77-98AB-860172DC7DA1
```

**Comment by mattleibow** [comment]
Hmm, at the end I see:

```
[01:55:10.9086960] Simulator configuration written to /var/folders/x1/2s1cq4312cx35w541x8d45mm0000gn/T/tmpdwBwve.tmp
[01:55:10.9273450] Process mlaunch exited with 0
[01:55:10.9295110] Simulator listing finished (37 kB)
[01:55:10.9540590] 
[01:55:10.9540680] Running /Applications/Xcode.app/Contents/Developer/usr/bin/simctl create "iPhone-5 (iOS 16.4) - created by XHarness" com.apple.CoreSimulator.SimDeviceType.iPhone-5 com.apple.CoreSimulator.SimRuntime.iOS-16-4
[01:55:11.4942230] Invalid device type: com.apple.CoreSimulator.SimDeviceType.iPhone-5
[01:55:11.4954400] Process simctl exited with 146
[01:55:11.4960340] Could not create device
runtime: com.apple.CoreSimulator.SimRuntime.iOS-16-4
device type: com.apple.CoreSimulator.SimDeviceType.iPhone-5
[01:55:11.5013290] Failed to find/create simulator (attempt 1/3):
Microsoft.DotNet.XHarness.Common.CLI.NoDeviceFoundException: Could not create device
runtime: com.apple.CoreSimulator.SimRuntime.iOS-16-4
device type: com.apple.CoreSimulator.SimDeviceType.iPhone-5
   at Microsoft.DotNet.XHarness.iOS.Shared.Hardware.SimulatorLoader.FindOrCreateDevicesAsync(ILog log, String runtime, String devicetype, Boolean force, CancellationToken cancellationToken) in /_/src/Microsoft.DotNet.XHarness.iOS.Shared/Hardware/SimulatorLoader.cs:line 232
   at Microsoft.DotNet.XHarness.iOS.Shared.Hardware.SimulatorLoader.FindSimulators(TestTargetOs target, ILog log, Boolean createIfNeeded, Boolean minVersion, CancellationToken cancellationToken) in /_/src/Microsoft.DotNet.XHarness.iOS.Shared/Hardware/SimulatorLoader.cs:line 412
   at Microsoft.DotNet.XHarness.iOS.Shared.Hardware.SimulatorLoader.FindSimulators(TestTargetOs target, ILog log, Int32 retryCount, Boolean createIfNeeded, Boolean minVersion, CancellationToken cancellationToken) in /_/src/Microsoft.DotNet.XHarness.iOS.Shared/Hardware/SimulatorLoader.cs:line 518
[01:55:11.5015310] 
[01:55:11.5015330] Running /Applications/Xcode.app/Contents/Developer/usr/bin/simctl create "iPhone-5 (iOS 16.4) - created by XHarness" com.apple.CoreSimulator.SimDeviceType.iPhone-5 com.apple.CoreSimulator.SimRuntime.iOS-16-4
[01:55:12.0288810] Invalid device type: com.apple.CoreSimulator.SimDeviceType.iPhone-5
[01:55:12.0298660] Process simctl exited with 146
[01:55:12.0299290] Could not create device
runtime: com.apple.CoreSimulator.SimRuntime.iOS-16-4
device type: com.apple.CoreSimulator.SimDeviceType.iPhone-5
[01:55:12.0303810] Failed to find/create simulator (attempt 2/3):
Microsoft.DotNet.XHarness.Common.CLI.NoDeviceFoundException: Could not create device
runtime: com.apple.CoreSimulator.SimRuntime.iOS-16-4
device type: com.apple.CoreSimulator.SimDeviceType.iPhone-5
   at Microsoft.DotNet.XHarness.iOS.Shared.Hardware.SimulatorLoader.FindOrCreateDevicesAsync(ILog log, String runtime, String devicetype, Boolean force, CancellationToken cancellationToken) in /_/src/Microsoft.DotNet.XHarness.iOS.Shared/Hardware/SimulatorLoader.cs:line 232
   at Microsoft.DotNet.XHarness.iOS.Shared.Hardware.SimulatorLoader.FindSimulators(TestTargetOs target, ILog log, Boolean createIfNeeded, Boolean minVersion, CancellationToken cancellationToken) in /_/src/Microsoft.DotNet.XHarness.iOS.Shared/Hardware/SimulatorLoader.cs:line 412
   at Microsoft.DotNet.XHarness.iOS.Shared.Hardware.SimulatorLoader.FindSimulators(TestTargetOs target, ILog log, Int32 retryCount, Boolean createIfNeeded, Boolean minVersion, CancellationToken cancellationToken) in /_/src/Microsoft.DotNet.XHarness.iOS.Shared/Hardware/SimulatorLoader.cs:line 518
[01:55:12.0305450] 
[01:55:12.0305490] Running /Applications/Xcode.app/Contents/Developer/usr/bin/simctl create "iPhone-5 (iOS 16.4) - created by XHarness" com.apple.CoreSimulator.SimDeviceType.iPhone-5 com.apple.CoreSimulator.SimRuntime.iOS-16-4
[01:55:12.5518000] Invalid device type: com.apple.CoreSimulator.SimDeviceType.iPhone-5
[01:55:12.5527090] Process simctl exited with 146
[01:55:12.5528280] Could not create device
runtime: com.apple.CoreSimulator.SimRuntime.iOS-16-4
device type: com.apple.CoreSimulator.SimDeviceType.iPhone-5
[01:55:12.5534830] Failed to find/create simulator (attempt 3/3):
Microsoft.DotNet.XHarness.Common.CLI.NoDeviceFoundException: Could not create device
runtime: com.apple.CoreSimulator.SimRuntime.iOS-16-4
device type: com.apple.CoreSimulator.SimDeviceType.iPhone-5
   at Microsoft.DotNet.XHarness.iOS.Shared.Hardware.SimulatorLoader.FindOrCreateDevicesAsync(ILog log, String runtime, String devicetype, Boolean force, CancellationToken cancellationToken) in /_/src/Microsoft.DotNet.XHarness.iOS.Shared/Hardware/SimulatorLoader.cs:line 232
   at Microsoft.DotNet.XHarness.iOS.Shared.Hardware.SimulatorLoader.FindSimulators(TestTargetOs target, ILog log, Boolean createIfNeeded, Boolean minVersion, CancellationToken cancellationToken) in /_/src/Microsoft.DotNet.XHarness.iOS.Shared/Hardware/SimulatorLoader.cs:line 412
   at Microsoft.DotNet.XHarness.iOS.Shared.Hardware.SimulatorLoader.FindSimulators(TestTargetOs target, ILog log, Int32 retryCount, Boolean createIfNeeded, Boolean minVersion, CancellationToken cancellationToken) in /_/src/Microsoft.DotNet.XHarness.iOS.Shared/Hardware/SimulatorLoader.cs:line 518
```

**Comment by mattleibow** [comment]
OK, so it seems I may have done the test wrong. So list does not find anything but mlaunch does and testing works at least:

I needed to use `--target ios-simulator-64` instead of `--target ios-simulator`. I assumed the presence of a -32 version meant the lack of any bit suffix was "system default".

**Comment by premun** [comment]
@mattleibow the way mlaunch is works is that it only lists "additional" simulators. So you have some version of Xcode (14.3.1) and that one comes with a specific version of Simulator inside. This one doesn't get listed for some reason. The others you add on top manually do.

It's also useful to check if mlaunch is not outdated in XHarness and needs a bump.

> I needed to use --target ios-simulator-64 instead of --target ios-simulator. I assumed the presence of a -32 version meant the lack of any bit suffix was "system default".

Did this fix your issue then?

**Comment by premun** [comment]
Ah, gotcha. Yeah, the `apple simulators` command set was just a basic port with no additional love or testing from our side.

The XHarness repo's ownership is now being changed to the runtime team. The .NET Engineering Services team was affected by the layoffs and half of the US team was moved to a different org so at the moment, we don't have the bandwidth to develop new features here. I believe the MAUI will have to invest in this themselves.
