### ISSUE TITLE
Exception loading  using apple state

### ISSUE THREAD

**Issue by rmarinho** [dotnet/xharness#1116]
When trying to look at the output of `xharess apple state` command to grab the connected devices we found this issue.

https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=8779898&view=logs&j=f0ced1d2-fef2-5ad8-51da-6bb4f4b3c74f&t=504594ad-821d-5f53-8267-94b646d4abc7&l=1121

version /9.0.0-prerelease.23577.1

```
Apple State: Process ID: 82943
Apple State: [9.0.0-prerelease.23577.1+c1238c21187506a3539e09ac9eba582a1fd7a74d] XHarness command issued: apple state --verbosity=Debug
Apple State: fail: Failed to load connected devices:
Apple State:       System.Exception: Failed to list devices.
Apple State:          at Microsoft.DotNet.XHarness.iOS.Shared.Hardware.HardwareDeviceLoader.LoadDevices(ILog log, Boolean includeLocked, Boolean forceRefresh, Boolean listExtraData, Boolean includeWirelessDevices, Cancellation*** cancellation***) in /_/src/Microsoft.DotNet.XHarness.iOS.Shared/Hardware/HardwareDeviceLoader.cs:line 104
Apple State:          at Microsoft.DotNet.XHarness.CLI.Commands.Apple.AppleStateCommand.InvokeInternal(ILogger logger) in /_/src/Microsoft.DotNet.XHarness.CLI/Commands/Apple/AppleStateCommand.cs:line 201
```

```
Apple State:       [18:57:03.9857070] error MT0000: Unexpected error - Please file a bug report at https://github.com/xamarin/xamarin-macios/issues/new
Apple State:       [18:57:04.1303550] System.NullReferenceException: Object reference not set to an instance of an object.
Apple State:       [18:57:04.1303780]    at Xamarin.Hosting.RealDevice.Connect***() in /Users/builder/azdo/_work/1/s/tools/mlaunch/Xamarin.Hosting/Xamarin.Hosting/RealDevice.cs:line 121
Apple State:       [18:57:04.1303790]    at System.Threading.Tasks.Task.InnerInvoke()
Apple State:       [18:57:04.1303800]    at System.Threading.Tasks.Task.<>c.<.cctor>b__273_0(Object)
Apple State:       [18:57:04.1303800]    at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread, ExecutionContext, ContextCallback, Object)
Apple State:       [18:57:04.1303810] --- End of stack trace from previous location ---
Apple State:       [18:57:04.1303810]    at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread, ExecutionContext, ContextCallback, Object)
Apple State:       [18:57:04.1303820]    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task&, Thread )
Apple State:       [18:57:04.1303820] --- End of stack trace from previous location ---
Apple State:       [18:57:04.1303830]    at Xamarin.Hosting.RealDevice.IsUnlockedAsync() in /Users/builder/azdo/_work/1/s/tools/mlaunch/Xamarin.Hosting/Xamarin.Hosting/RealDevice.cs:line 192
Apple State:       [18:57:04.1303900]    at Xamarin.Launcher.DevController.GetDeviceInfoAsync(RealDevice, Boolean) in /Users/builder/azdo/_work/1/s/tools/mlaunch/Xamarin.Hosting/Xamarin.Launcher/controller-device.cs:line 678
Apple State:       [18:57:04.1303900]    at Xamarin.Launcher.DevController.<>c__DisplayClass22_1.<<GetDevicesAsyncUsingAMDevice>b__2>d.MoveNext() in /Users/builder/azdo/_work/1/s/tools/mlaunch/Xamarin.Hosting/Xamarin.Launcher/controller-device.cs:line 552
Apple State:       [18:57:04.1430710] Process mlaunch exited with 1
Apple State:       [18:57:04.1639860] Failed to parse device list: System.Exception: Failed to list devices.
Apple State:          at Microsoft.DotNet.XHarness.iOS.Shared.Hardware.HardwareDeviceLoader.LoadDevices(ILog log, Boolean includeLocked, Boolean forceRefresh, Boolean listExtraData, Boolean includeWirelessDevices, Cancellation*** cancellation***) in /_/src/Microsoft.DotNet.XHarness.iOS.Shared/Hardware/HardwareDeviceLoader.cs:line 104
Apple State:       

```

https://github.com/xamarin/xamarin-macios/issues/19598

**Comment by akoeplinger** [comment]
This is an mlaunch issue, tracking it with https://github.com/xamarin/xamarin-macios/issues/19598
