### ISSUE TITLE
XCode 15.3 support

### ISSUE THREAD

**Issue by vaind** [dotnet/xharness#1171]
```shell
$ xharness apple simulators list                                                                       
[9.0.0-prerelease.24161.1+134035492ed8154fc9c5a930a4ca52c422b21afb] XHarness command issued: apple simulators list
crit: System.Exception: Failed to detect Xcode UUID!
         at Microsoft.DotNet.XHarness.CLI.Commands.Apple.Simulators.SimulatorsCommand.GetXcodeInformation() in /_/src/Microsoft.DotNet.XHarness.CLI/Commands/Apple/Simulators/SimulatorsCommand.cs:line 401
         at Microsoft.DotNet.XHarness.CLI.Commands.Apple.Simulators.SimulatorsCommand.GetSimulatorIndexXml() in /_/src/Microsoft.DotNet.XHarness.CLI/Commands/Apple/Simulators/SimulatorsCommand.cs:line 304
         at Microsoft.DotNet.XHarness.CLI.Commands.Apple.Simulators.SimulatorsCommand.GetAvailableSimulators() in /_/src/Microsoft.DotNet.XHarness.CLI/Commands/Apple/Simulators/SimulatorsCommand.cs:line 95
         at Microsoft.DotNet.XHarness.CLI.Commands.Apple.Simulators.ListCommand.InvokeInternal(ILogger logger) in /_/src/Microsoft.DotNet.XHarness.CLI/Commands/Apple/Simulators/ListCommand.cs:line 33
         at Microsoft.DotNet.XHarness.CLI.Commands.XHarnessCommand`1.Invoke(IEnumerable`1 arguments) in /_/src/Microsoft.DotNet.XHarness.CLI/Commands/XHarnessCommand.cs:line 145
XHarness exit code: 71 (GENERAL_FAILURE)
```

The failing code:

https://github.com/dotnet/xharness/blob/a496e7e9e4d445b420dc818c157073ee3e6b16c1/src/Microsoft.DotNet.XHarness.CLI/Commands/Apple/Simulators/SimulatorsCommand.cs#L398-L402

And what I get when I run it manually: 

```shell
$/usr/libexec/PlistBuddy -c 'Print DVTPlugInCompatibilityUUID' /Applications/Xcode-15.3.0.app/Contents/Info.plist
Print: Entry, "DVTPlugInCompatibilityUUID", Does Not Exist
```

**Comment by akoeplinger** [comment]
Thanks for the report, opened https://github.com/dotnet/xharness/pull/1172
