### ISSUE TITLE
Shipped adb is x86_64 only

### ISSUE THREAD

**Issue by borrrden** [dotnet/xharness#1200]
This means all commands on Apple silicon fail with the following (unless using rosetta and the entire dotnet runtime is x86_64 I guess?):

```
$HOME/.dotnet/tools/xharness android state
[8.0.0-prerelease.24229.2+aacfb6328fdef17e572617bbb551431bb9cb1ff2] XHarness command issued: android state
crit: Error: An error occurred trying to start process '/Users/couchbase/.dotnet/tools/.store/microsoft.dotnet.xharness.cli/8.0.0-prerelease.24229.2/microsoft.dotnet.xharness.cli/8.0.0-prerelease.24229.2/runtimes/any/native/adb/macos/adb' with working directory '/Users/couchbase/.dotnet/tools/.store/microsoft.dotnet.xharness.cli/8.0.0-prerelease.24229.2/microsoft.dotnet.xharness.cli/8.0.0-prerelease.24229.2/runtimes/any/native/adb/macos'. Bad CPU type in executable
      System.ComponentModel.Win32Exception (86): An error occurred trying to start process '/Users/couchbase/.dotnet/tools/.store/microsoft.dotnet.xharness.cli/8.0.0-prerelease.24229.2/microsoft.dotnet.xharness.cli/8.0.0-prerelease.24229.2/runtimes/any/native/adb/macos/adb' with working directory '/Users/couchbase/.dotnet/tools/.store/microsoft.dotnet.xharness.cli/8.0.0-prerelease.24229.2/microsoft.dotnet.xharness.cli/8.0.0-prerelease.24229.2/runtimes/any/native/adb/macos'. Bad CPU type in executable
         at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
         at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
         at Microsoft.DotNet.XHarness.Android.Execution.AdbProcessManager.Run(String adbExePath, IEnumerable`1 arguments, TimeSpan timeOut) in /_/src/Microsoft.DotNet.XHarness.Android/Execution/AdbProcessManager.cs:line 74
         at Microsoft.DotNet.XHarness.Android.AdbRunner.RunAdbCommand(IEnumerable`1 arguments, TimeSpan timeOut) in /_/src/Microsoft.DotNet.XHarness.Android/AdbRunner.cs:line 1095
         at Microsoft.DotNet.XHarness.Android.AdbRunner.RunAdbCommand(String[] arguments) in /_/src/Microsoft.DotNet.XHarness.Android/AdbRunner.cs:line 1086
         at Microsoft.DotNet.XHarness.Android.AdbRunner.GetAdbVersion() in /_/src/Microsoft.DotNet.XHarness.Android/AdbRunner.cs:line 115
         at Microsoft.DotNet.XHarness.CLI.Commands.Android.AndroidStateCommand.GetStateData(ILogger logger) in /_/src/Microsoft.DotNet.XHarness.CLI/Commands/Android/AndroidStateCommand.cs:line 100
         at Microsoft.DotNet.XHarness.CLI.Commands.Android.AndroidStateCommand.InvokeInternal(ILogger logger) in /_/src/Microsoft.DotNet.XHarness.CLI/Commands/Android/AndroidStateCommand.cs:line 35
XHarness exit code: 71 (GENERAL_FAILURE)
```

**Comment by borrrden** [comment]
This isn't mentioned in the docs but I found out that the `ADB_EXE_PATH` environment variable can point xharness somewhere else.

**Comment by ivanpovazan** [comment]
@akoeplinger the adb we are shipping comes from: https://github.com/dotnet/xharness/blob/718b5a12f619fe4d4794b80bee5f3da38bcc6400/src/Microsoft.DotNet.XHarness.CLI/Microsoft.DotNet.XHarness.CLI.csproj#L21 
Running `file adb` on it gives:
```
adb: Mach-O 64-bit executable x86_64
```

Looking at the releases in 32.0.0. they started shipping the universal binary for Apple M1 devices: https://developer.android.com/tools/releases/platform-tools#3200_january_2022

Running `file adb` on it gives:
```
adb: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64] [arm64]
adb (for architecture x86_64):  Mach-O 64-bit executable x86_64
adb (for architecture arm64):   Mach-O 64-bit executable arm64
```

Should we bump the version we are downloading/shipping?

**Comment by akoeplinger** [comment]
Yes that makes sense.

I think the existing binary should work too though assuming you install Rosetta since we just shell out to it so the host dotnet architecture shouldn't matter.

**Comment by borrrden** [comment]
Rosetta is not something you "install" is it?  Isn't it just part of the OS?
