### ISSUE TITLE
Fix ActiveIssue change

### ISSUE THREAD

**Issue by akoeplinger** [dotnet/xharness#137]
The change in https://github.com/dotnet/xharness/pull/130 is wrong/unnecessary as it skips test methods with the attribute rather than skipping the `category=failing` trait generated by the [ActiveIssueDiscoverer](https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.XUnitExtensions/src/Discoverers/ActiveIssueDiscoverer.cs) in the arcade xunit extensions.

We should instead just pass the -notrait in.

**Comment by akoeplinger** [comment]
@mandel-macaque

**Comment by EgorBo** [comment]
Tried the latest xharness (20230.1) and crashes
```
Unhandled Exception:
System.ArgumentNullException: Value cannot be null. (Parameter 'key')
   at System.Collections.Concurrent.ConcurrentDictionary`2[[System.Type, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.AttributeUsageAttribute, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ThrowKeyNullException()
   at System.Collections.Concurrent.ConcurrentDictionary`2[[System.Type, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.AttributeUsageAttribute, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].GetOrAdd(Type key, Func`2 valueFactory)
   at Xunit.Sdk.ReflectionAttributeInfo.GetAttributeUsage(Type attributeType) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Reflection\ReflectionAttributeInfo.cs:line 57
   at Xunit.Sdk.ReflectionMethodInfo.GetCustomAttributes(MethodInfo method, String assemblyQualifiedAttributeTypeName) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Reflection\ReflectionMethodInfo.cs:line 87
   at Xunit.Sdk.ReflectionMethodInfo.GetCustomAttributes(String assemblyQualifiedAttributeTypeName) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Reflection\ReflectionMethodInfo.cs:line 80
   at Microsoft.DotNet.XHarness.Tests.Runners.Xunit.XUnitTestRunner.IsIncluded(ITestCase testCase)
   at Microsoft.DotNet.XHarness.Tests.Runners.Xunit.XUnitTestRunner.<Run>b__86_0(ITestCase tc)
   at System.Linq.Enumerable.WhereListIterator`1[[Xunit.Abstractions.ITestCase, xunit.abstractions, Version=2.0.0.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]].ToList()
   at System.Linq.Enumerable.ToList[ITestCase](IEnumerable`1 source)
   at Microsoft.DotNet.XHarness.Tests.Runners.Xunit.XUnitTestRunner.Run(Assembly assembly, String assemblyPath)
   at Microsoft.DotNet.XHarness.Tests.Runners.Xunit.XUnitTestRunner.Run(IEnumerable`1 testAssemblies)
   at Microsoft.DotNet.XHarness.Tests.Runners.ApplicationEntryPoint.InternalRunAsync(LogWriter logger)
   at Microsoft.DotNet.XHarness.Tests.Runners.Core.iOSApplicationEntryPoint.RunAsync()
   at SimpleTestRunner.Main(String[] args) in /Users/egorbo/prj/runtime/src/mono/msbuild/AppleTestRunner/AppleTestRunner.cs:line 88
   at SimpleTestRunner.<Main>(String[] args)
```

**Comment by mandel-macaque** [comment]
@akoeplinger the -notrait is already supported in the runner via the traits file, that has to be provided by the subclass of the entry point. If the trait is failing, and is present, I don't know why I got a bug asking to support the filtering via the attribute. I'm getting confused.

From my point of view:

* Do we support traits: Yes, we always had. If that is what is needed, is already present following the file format we agreed for xamarin-macios and it has worked fine since we started using the mono bin artefacts.
* Do we need to support filtering per Attributes: I personally, don't like it, but it is not clear to me. 

I'll partially revert the commit, since it added some tests that were missing.

@EgorBo please pass the trait via the traits file like the ApplicationExtension abstract class has as a property. The format is the same as the one present in the traits file that is provided by mono (@akoeplinger and I agreed on a very simple format, no need for -notrait, is just a key value pair).

**Comment by akoeplinger** [comment]
As discussed on Slack, we only need filtering via traits so the attributes filter can be removed.
