### ISSUE TITLE
Tunnel fails on 32b devices

### ISSUE THREAD

**Issue by mandel-macaque** [dotnet/xharness#168]
Most runs work, but we have the following error:

```
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.NetworkStream'.
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at Microsoft.DotNet.XHarness.iOS.Shared.Listeners.SimpleTcpListener.Processing() in /Users/mandel/Xamarin/xharness/src/Microsoft.DotNet.XHarness.iOS.Shared/Listeners/SimpleTcpListener.cs:line 193
   at Microsoft.DotNet.XHarness.iOS.Shared.Listeners.SimpleTcpListener.StartTcpTunnel() in /Users/mandel/Xamarin/xharness/src/Microsoft.DotNet.XHarness.iOS.Shared/Listeners/SimpleTcpListener.cs:line 156
```

**Comment by premun** [comment]
This is possibly resolved by the `IDisposable` refactoring I have made and doesn't seem like it's related to 32 bit. Closing
