### ISSUE TITLE
[iOS] Listing simulators hangs

### ISSUE THREAD

**Issue by premun** [dotnet/xharness#196]
We are occasionally getting exceptions when listing simulators:
```
[06:20:31] info: test[0]
      Starting test for ios-simulator-64..
[06:20:31] info: test[0]
      Starting application 'System.Numerics.Vectors.Tests' on ios-simulator-64
[06:21:22] fail: test[0]
      Application run failed:
      System.Exception: Failed to list simulators.
         at Microsoft.DotNet.XHarness.iOS.Shared.Hardware.SimulatorLoader.<>c__DisplayClass16_0.<<LoadDevices>b__0>d.MoveNext() in /_/src/Microsoft.DotNet.XHarness.iOS.Shared/Hardware/SimulatorLoader.cs:line 81
      --- End of stack trace from previous location where exception was thrown ---
         at Microsoft.DotNet.XHarness.iOS.Shared.Hardware.SimulatorLoader.LoadDevices(ILog log, Boolean includeLocked, Boolean forceRefresh, Boolean listExtraData) in /_/src/Microsoft.DotNet.XHarness.iOS.Shared/Hardware/SimulatorLoader.cs:line 62
         at Microsoft.DotNet.XHarness.iOS.AppRunner.RunApp(AppBundleInformation appInformation, TestTarget target, TimeSpan timeout, TimeSpan testLaunchTimeout, String deviceName, String companionDeviceName, Boolean ensureCleanSimulatorState, Int32 verbosity, XmlResultJargon xmlResultJargon, CancellationToken cancellationToken) in /_/src/Microsoft.DotNet.XHarness.iOS/AppRunner.cs:line 201
         at Microsoft.DotNet.XHarness.CLI.Commands.iOS.iOSTestCommand.RunTest(ILogger logger, TestTarget target, Logs logs, ProcessManager processManager, IHardwareDeviceLoader deviceLoader, ISimulatorLoader simulatorLoader, ITunnelBore tunnelBore, CancellationToken cancellationToken) in /_/src/Microsoft.DotNet.XHarness.CLI/Commands/iOS/iOSTestCommand.cs:line 158
XHarness exit code: 1004
```

The real problem is inside the [`list-simulators.log`](https://helixre107v0xd6tv7v8isja.blob.core.windows.net/dotnet-xharness-refs-pull-195-merge-a1a285d820544dc3a5/WorkItem/simulator-list-20200514_062032.log?sv=2019-02-02&se=2020-06-03T13%3A20%3A07Z&sr=c&sp=rl&sig=buL428Vbe0hZgTBCLyAj%2F83gxsEHgRL3BZxSECBdSnQ%3D) file:
```
06:20:32.0390850 /Users/helix-runner/.nuget/packages/microsoft.dotnet.xharness.cli/1.0.0-ci/tools/netcoreapp3.1/any/../../../runtimes/any/native/mlaunch/bin/mlaunch --listsim=/tmp/tmpnrCJeL.tmp --output-format=XML
06:20:32.0415030 Launching /Users/helix-runner/.nuget/packages/microsoft.dotnet.xharness.cli/1.0.0-ci/tools/netcoreapp3.1/any/../../../runtimes/any/native/mlaunch/bin/mlaunch --listsim=/tmp/tmpnrCJeL.tmp --output-format=XML
06:21:02.2068950 Pids to kill: 14456
06:21:02.2069620 Writing process list:
06:21:02.2071830 ps -A -o pid,ruser,ppid,pgid,%cpu=%CPU,%mem=%MEM,flags=FLAGS,lstart,rss,vsz,tty,state,time,command
06:21:02.3193080   PID RUSER             PPID  PGID  %CPU %MEM    FLAGS STARTED                         RSS      VSZ TTY      STAT      TIME COMMAND
06:21:02.8820750     1 root                 0     1   0.0  0.1     4004 Wed May 13 04:05:54 2020      17404  4312932 ??       Ss     0:54.65 /sbin/launchd
06:21:02.8824150    64 root                 1    64   0.0  0.0     4004 Wed May 13 04:06:46 2020       1180  4306048 ??       Ss     0:00.58 /usr/sbin/syslogd
...

...
06:21:03.1160680   507 helix-runner       440   507   0.0  0.0     4106 Wed May 13 04:06:59 2020       4536  4304892 ttys000  Ss     0:00.03 login -pf helix-runner
06:21:03.1161000   508 helix-runner       507   508   0.0  0.0     4006 Wed May 13 04:06:59 2020       1448  4296768 ttys000  S+     0:00.02 -bash
06:21:03.1588760 Printing backtrace for pid=14456
06:21:03.1590780 /usr/bin/lldb --source /tmp/tmp0MsCKj.tmp
06:21:21.1347290 Simulator configuration written to /tmp/tmpnrCJeL.tmp
06:21:22.0926450 (lldb) command source -s 0 '/tmp/tmp0MsCKj.tmp'
06:21:22.0930750 Executing commands in '/tmp/tmp0MsCKj.tmp'.
06:21:22.0932030 (lldb) process attach --pid 14456
06:21:22.2427410 error: attach failed: Error 1
```

Full logs here: https://helix.int-dot.net/api/2019-06-17/jobs/a1a285d8-2054-4dc3-a5be-3da56eba840e/workitems/WorkItem

**Comment by premun** [comment]
@mandel-macaque this seems to happen only on one machines - `dci-mac-build-048`. I tried running XHarness there manually and it succeeded fine. I will try with the Debug package from the build

**Comment by premun** [comment]
Hm, weird, I tried again with the exact same nupkg as used in the failing build (I had a new bad one) and it succeeded...

**Comment by premun** [comment]
Ok, this is becoming a priority now - we are seeing it in the other OSX queues that I rolled out Xcode too

**Comment by premun** [comment]
So what is actually happening here is that mlaunch hangs and gets killed by timeout

**Comment by premun** [comment]
I have done a lot of testing and it all comes down to an exception being thrown from this line:
```csharp
                log.WriteLine("Result:" + Environment.NewLine + File.ReadAllText(tmpfile));
```
the exception being:
```
      System.Exception: Failed to list simulators.
         at Microsoft.DotNet.XHarness.iOS.Shared.Hardware.SimulatorLoader.LoadDevices(ILog log, Boolean includeLocked, Boolean forceRefresh, Boolean listExtraData) in /_/src/Microsoft.DotNet.XHarness.iOS.Shared/Hardware/SimulatorLoader.cs:line 79
         at Microsoft.DotNet.XHarness.iOS.AppRunner.FindSimulators(TestTarget target) in /_/src/Microsoft.DotNet.XHarness.iOS/AppRunner.cs:line 531
```

which doesn't make much sense to me..

**Comment by premun** [comment]
Latest investigations show that it is not a hang but an exception where mlaunch returns content successfully but returns non-zero exit code.
The hang was caused by everything being wrapped in `Task.Run(() => ...)` and not getting the exception out rightaway.

**Comment by premun** [comment]
Looks like mlaunch sometimes times out but publishes the device list successfully and in those cases we don't have to fail.

Sometimes mlaunch returns the exit code 137 and fails

**Comment by premun** [comment]
Retry logic seems to fix this, I ran 60 jobs and no occurrence. Before was 1-2 times per 10 jobs
