### ISSUE TITLE
RunOnDeviceWithSkippedClassesTest is flaky

### ISSUE THREAD

**Issue by premun** [dotnet/xharness#225]
Getting the local IP addresses for the Mlaunch arguments failed but maybe not a big deal:
https://dev.azure.com/dnceng/public/_build/results?buildId=657170&view=ms.vss-test-web.build-test-results-tab&runId=20395630&resultId=100335&paneView=debug

**Error message**
```
System.Net.Internals.SocketExceptionFactory+ExtendedSocketException : nodename nor servname provided, or not known
```

**Stack trace**
```
   at System.Net.Dns.GetHostEntryOrAddressesCore(String hostName, Boolean justAddresses)
   at System.Net.Dns.GetHostEntry(String hostNameOrAddress)
   at Microsoft.DotNet.XHarness.iOS.AppRunner.GetDeviceArguments(AppBundleInformation appInformation, String deviceName, Boolean isWatchTarget) in /_/src/Microsoft.DotNet.XHarness.iOS/AppRunner.cs:line 475
   at Microsoft.DotNet.XHarness.iOS.AppRunner.RunApp(AppBundleInformation appInformation, TestTarget target, TimeSpan timeout, TimeSpan testLaunchTimeout, String deviceName, String companionDeviceName, Boolean ensureCleanSimulatorState, Int32 verbosity, XmlResultJargon xmlResultJargon, String[] skippedMethods, String[] skippedTestClasses, CancellationToken cancellationToken) in /_/src/Microsoft.DotNet.XHarness.iOS/AppRunner.cs:line 162
   at Microsoft.DotNet.XHarness.iOS.Tests.AppRunnerTests.RunOnDeviceWithSkippedClassesTestTest(String[] skippedClasses) in /_/tests/Microsoft.DotNet.XHarness.iOS.Tests/AppRunnerTests.cs:line 654
--- End of stack trace from previous location ---
```

**Comment by mandel-macaque** [comment]
That is due to the network setup, happens when the router cannot find the device. Are we using the usb? We might want to do something about it where we ignore the error.

**Comment by premun** [comment]
This was fixed by introduction of `GetLocalIpAddresses()` on `IHelpers`
