### ISSUE TITLE
Android failed the Arcade CI

### ISSUE THREAD

**Issue by premun** [dotnet/xharness#232]
```console
[20:10:57] fail: test[0]
      No value for 'return-code' provided in instrumentation result.  This may indicate a crashed test (see log)
[20:11:00] dbug: test[0]
      Executing command: '/home/helixbot/work/B0C90971/p/xharness-cli/.store/microsoft.dotnet.xharness.cli/1.0.0-prerelease.20277.1/microsoft.dotnet.xharness.cli/1.0.0-prerelease.20277.1/runtimes/any/native/adb/linux/adb -s emulator-5556 logcat -d '
[20:11:01] info: test[0]
      Wrote current ADB log to /home/helixbot/work/B0C90971/w/A1C80906/uploads/adb-logcat-net.dot.System.Numerics.Vectors.Tests.log
[20:11:01] info: test[0]
      Attempting to remove apk 'net.dot.System.Numerics.Vectors.Tests': 
[20:11:01] dbug: test[0]
      Executing command: '/home/helixbot/work/B0C90971/p/xharness-cli/.store/microsoft.dotnet.xharness.cli/1.0.0-prerelease.20277.1/microsoft.dotnet.xharness.cli/1.0.0-prerelease.20277.1/runtimes/any/native/adb/linux/adb -s emulator-5556 uninstall net.dot.System.Numerics.Vectors.Tests'
[20:11:02] info: test[0]
      Successfully uninstalled net.dot.System.Numerics.Vectors.Tests.
[20:11:02] fail: test[0]
      Non-success instrumentation exit code: 1106
XHarness exit code: 1001
+ export _commandExitCode=233
```

Full logs: https://helix.dot.net/api/2019-06-17/jobs/de03a1d5-01aa-4c76-80c4-8a9d49186a7e/workitems/xharness-System.Numerics.Vectors.Tests-x86/console

Build: https://dev.azure.com/dnceng/public/_build/results?buildId=661523&view=logs&j=21143b0a-ace1-5058-215e-b11404388d17&s=ee3800fd-6e81-525f-e564-94108585217d

Note: This is after the bump done in https://github.com/dotnet/arcade/pull/5555
![image](https://user-images.githubusercontent.com/7013027/83112990-454f9180-a0c7-11ea-9c52-0bc73f666ea8.png)

**Comment by MattGal** [comment]
This is unrelated to the version bump, it's just a crash in the app:

```
05-27 20:10:57.464  1793  3458 W Binder  : java.lang.Throwable
05-27 20:10:57.464  1793  3458 W Binder  : 	at android.os.BinderProxy.transact(BinderProxy.java:480)
05-27 20:10:57.464  1793  3458 W Binder  : 	at android.app.IInstrumentationWatcher$Stub$Proxy.instrumentationFinished(IInstrumentationWatcher.java:205)
05-27 20:10:57.464  1793  3458 W Binder  : 	at com.android.server.am.InstrumentationReporter$MyThread.run(InstrumentationReporter.java:86)
05-27 20:10:57.476  1793  1817 E memtrack: Couldn't load memtrack module
05-27 20:10:57.476  1793  1817 W android.os.Debug: failed to get memory consumption info: -1
05-27 20:10:57.489  1535  1535 I Zygote  : Process 3428 exited due to signal 9 (Killed)
05-27 20:10:57.494  1793  1820 I libprocessgroup: Successfully killed process cgroup uid 10104 pid 3428 in 41ms
05-27 20:10:57.495  3418  3418 D AndroidRuntime: Shutting down VM
05-27 20:10:57.515  1793  3458 I ActivityManager: Failure reporting to instrumentation watcher: comp=ComponentInfo{net.dot.System.Numerics.Vectors.Tests/net.dot.MonoRunner} results=Bundle[mParcelledData.dataSize=296]
```
