### ISSUE TITLE
lldb backtrace fails with an exception when lldb is not installed

### ISSUE THREAD

**Issue by akoeplinger** [dotnet/xharness#268]
Saw this on a Helix run:
```
[40m[32minfo[39m[22m[49m: test[0]
      05:28:27.3839256 /usr/bin/lldb --source /tmp/tmprrsiyZ.tmp
      
[41m[1m[37mcrit[39m[22m[49m: test[0]
      System.ComponentModel.Win32Exception (2): No such file or directory
         at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
         at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
         at System.Diagnostics.Process.Start()
         at Microsoft.DotNet.XHarness.Common.Execution.ProcessManager.RunAsyncInternal(Process process, ILog log, ILog stdout, ILog stderr, Action`2 kill, Func`3 getChildrenPS, Nullable`1 timeout, Dictionary`2 environmentVariables, Nullable`1 cancellationToken, Nullable`1 diagnostics) in /_/src/Microsoft.DotNet.XHarness.Common/Execution/ProcessManager.cs:line 282
         at Microsoft.DotNet.XHarness.Common.Execution.ProcessManager.KillTreeAsyncInternal(Int32 pid, Action`2 kill, Func`3 getChildrenPS, ILog log, Nullable`1 diagnostics) in /_/src/Microsoft.DotNet.XHarness.Common/Execution/ProcessManager.cs:line 156
         at Microsoft.DotNet.XHarness.Common.Execution.ProcessManager.RunAsyncInternal(Process process, ILog log, ILog stdout, ILog stderr, Action`2 kill, Func`3 getChildrenPS, Nullable`1 timeout, Dictionary`2 environmentVariables, Nullable`1 cancellationToken, Nullable`1 diagnostics) in /_/src/Microsoft.DotNet.XHarness.Common/Execution/ProcessManager.cs:line 313
         at Microsoft.DotNet.XHarness.Common.Execution.ProcessManager.ExecuteCommandAsync(String filename, IList`1 args, ILog log, ILog stdout, ILog stderr, TimeSpan timeout, Dictionary`2 environmentVariables, Nullable`1 cancellationToken) in /_/src/Microsoft.DotNet.XHarness.Common/Execution/ProcessManager.cs:line 58
         at Microsoft.DotNet.XHarness.CLI.Commands.Wasm.WasmTestCommand.InvokeInternal(ILogger logger) in /_/src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/WasmTestCommand.cs:line 71
         at Microsoft.DotNet.XHarness.Common.CLI.Commands.XHarnessCommand.Invoke(IEnumerable`1 arguments) in /_/src/Microsoft.DotNet.XHarness.Common/CLI/Commands/XHarnessCommand.cs:line 119
XHarness exit code: 1001
```

We should probably catch the exception when lldb can't be found.

/cc @premun

**Comment by premun** [comment]
@akoeplinger I will look into it

In the meantime - looks like you haven't set the proper env variables to make the logs look a bit better:
```bash
export XHARNESS_DISABLE_COLORED_OUTPUT=true
export XHARNESS_LOG_WITH_TIMESTAMPS=true
```
