### ISSUE TITLE
Device Acquisition Timeout on Android Devices

### ISSUE THREAD

**Issue by steveisok** [dotnet/xharness#308]
As part of https://github.com/dotnet/runtime/pull/42209, we ran into the follow failure:

#### Microsoft.Extensions.Configuration.Xml.Tests

[Log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-42209-merge-d87f39a1bd164984be/Microsoft.Extensions.Configuration.Xml.Tests/console.e9d49f12.log?sv=2019-07-07&se=2020-10-07T18%3A26%3A16Z&sr=c&sp=rl&sig=iwpzzVB%2BzFvQ6nYv6OJLuwHAIPHWiz7MXskNYCsUUFo%3D)

```
[11:26:36] info: test[0]
      Waiting for device to be available (max 5 minutes)
[11:26:36] dbug: test[0]
      Executing command: 'C:\h\w\AE270924\p\microsoft.dotnet.xharness.cli\1.0.0-prerelease.20457.1\runtimes\any\native\adb\windows\adb.exe -s 023AYV0V1W wait-for-device'
[11:31:37] fail: test[0]
      Waiting for command timed out: execution may be compromised.
[11:31:37] crit: test[0]
      Failure to run test package: Process must exit before requested information can be determined.
System.InvalidOperationException: Process must exit before requested information can be determined.
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.get_ExitCode()
   at Microsoft.DotNet.XHarness.Android.Execution.AdbProcessManager.Run(String adbExePath, String arguments, TimeSpan timeOut) in /_/src/Microsoft.DotNet.XHarness.Android/Execution/AdbProcessManager.cs:line 88
   at Microsoft.DotNet.XHarness.Android.AdbRunner.RunAdbCommand(String command, TimeSpan timeOut) in /_/src/Microsoft.DotNet.XHarness.Android/AdbRunner.cs:line 441
   at Microsoft.DotNet.XHarness.Android.AdbRunner.WaitForDevice() in /_/src/Microsoft.DotNet.XHarness.Android/AdbRunner.cs:line 121
   at Microsoft.DotNet.XHarness.CLI.Commands.Android.AndroidTestCommand.InvokeInternal(ILogger logger) in /_/src/Microsoft.DotNet.XHarness.CLI/Commands/Android/AndroidTestCommand.cs:line 102
XHarness exit code: 1001
```

Seems to be centered around trying to get a device to run.

**Comment by greenEkatherine** [comment]
I don't see timeouts in tests any more https://dev.azure.com/dnceng/public/_test/analytics?definitionId=686&contextType=build, closed

**Comment by premun** [comment]
@greenEkatherine I am not sure it would appear on this dashboard to be honest

**Comment by greenEkatherine** [comment]
@premun I've checked logs a failed tests as well. Should I check somewhere else?

**Comment by greenEkatherine** [comment]
As discussed offline with @premun I've also checked recent failed jobs in runtime-staging pipeline - they look also fine, no timeouts like this.
