### ISSUE TITLE
Occasional DirectoryNotFoundException in ios state command

### ISSUE THREAD

**Issue by premun** [dotnet/xharness#337]
The `ios state` command fails occasionally in Arcade CI:
```
XHarness command issued: ios state
[08:13:34] crit: System.IO.DirectoryNotFoundException: Could not find a part of the path '/Library/Contents/version.plist'.
    at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
    at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
    at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy, RequestCachePolicy cachePolicy)
    at System.Xml.XmlUrlResolver.GetEntity(Uri absoluteUri, String role, Type ofObjectToReturn)
    at System.Xml.XmlTextReaderImpl.OpenUrl()
    at System.Xml.XmlTextReaderImpl.Read()
    at System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader reader, Boolean preserveWhitespace)
    at System.Xml.XmlDocument.Load(XmlReader reader)
    at System.Xml.XmlDocument.Load(String filename)
    at Microsoft.DotNet.XHarness.Common.Execution.MacOSProcessManager.get_XcodeVersion() in /_/src/Microsoft.DotNet.XHarness.Common/Execution/MacOSProcessManager.cs:line 44
    at Microsoft.DotNet.XHarness.CLI.Commands.iOS.iOSGetStateCommand.InvokeInternal(ILogger logger) in /_/src/Microsoft.DotNet.XHarness.CLI/Commands/iOS/iOSGetStateCommand.cs:line 162
    at Microsoft.DotNet.XHarness.Common.CLI.Commands.XHarnessCommand.Invoke(IEnumerable`1 arguments) in /_/src/Microsoft.DotNet.XHarness.Common/CLI/Commands/XHarnessCommand.cs:line 120
```

Example:
https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-arcade-refs-pull-6457-merge-f5245acd21af418fb7/xharness-ios-state/console.31a57d73.log?sv=2019-07-07&se=2020-11-15T15%3A13%3A27Z&sr=c&sp=rl&sig=4susiF7HbchtXKfX6%2Bt%2Fg%2FK389duEngtCR%2FIsyjuwWY%3D

**Comment by premun** [comment]
Also this Arcade step should fail the build after this is resolved.

**Comment by premun** [comment]
This steps was failing because one of the machines didn't have `xcode-select` pointing to the Xcode installation but to the Xcode command line tools. That's why it only failed occasionally when it hit this one machine.

I verified that this machine was the only one with this issue:
```sql
WorkItems
| where QueueName == "osx.1015.amd64.open" and Started > now()-30d and FriendlyName == "xharness-ios-state" and Status != "Pass"
```

Error message improved here https://github.com/dotnet/xharness/pull/349
