### ISSUE TITLE
NullReferenceException when "getprop ro.product.cpu.abi" times out

### ISSUE THREAD

**Issue by akoeplinger** [dotnet/xharness#430]
Saw this here: https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-47344-merge-5a6c8098772545e0bb/Microsoft.Extensions.DependencyModel.Tests/console.070bf74d.log?sv=2019-07-07&se=2021-02-14T23%3A59%3A26Z&sr=c&sp=rl&sig=9t3%2FjnZR19lAaIBfy%2FQIdPKl3sxScllglrVTOxr5T8s%3D

```
[15:59:37] dbug: Executing command: 'C:\h\w\A76F0978\p\microsoft.dotnet.xharness.cli\1.0.0-prerelease.21068.3\runtimes\any\native\adb\windows\adb.exe  devices -l'
[15:59:37] dbug: Evaluating output line for device serial: 9CJAY1PTHW             device product:sargo model:Pixel_3a device:sargo transport_id:48
[15:59:37] dbug: Executing command: 'C:\h\w\A76F0978\p\microsoft.dotnet.xharness.cli\1.0.0-prerelease.21068.3\runtimes\any\native\adb\windows\adb.exe  -s 9CJAY1PTHW shell getprop ro.product.cpu.abi'
[16:04:37] fail: Waiting for command timed out: execution may be compromised.
[16:04:37] fail: Error trying to get device architecture: 
[16:04:37] crit: Failure to run test package: Object reference not set to an instance of an object.
                 System.NullReferenceException: Object reference not set to an instance of an object.
                    at Microsoft.DotNet.XHarness.CLI.Commands.Android.AndroidTestCommand.<>c__DisplayClass17_0.<GetDeviceToUse>b__0(KeyValuePair`2 kvp) in /_/src/Microsoft.DotNet.XHarness.CLI/Commands/Android/AndroidTestCommand.cs:line 259
                    at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
                    at Microsoft.DotNet.XHarness.CLI.Commands.Android.AndroidTestCommand.GetDeviceToUse(ILogger logger, AdbRunner runner, String apkRequiredArchitecture) in /_/src/Microsoft.DotNet.XHarness.CLI/Commands/Android/AndroidTestCommand.cs:line 259
                    at Microsoft.DotNet.XHarness.CLI.Commands.Android.AndroidTestCommand.InvokeInternal(ILogger logger) in /_/src/Microsoft.DotNet.XHarness.CLI/Commands/Android/AndroidTestCommand.cs:line 99
XHarness exit code: 71
```

The fact that we couldn't get the device architecture shouldn't cause a NullReferenceException.

/cc @MattGal

**Comment by MattGal** [comment]
I will take this and try to get it fixed today, but from the logs this doesn't seem to be the latest XHarness Arcade version; we probably want to use its ability to do infra retry / reboot when such a call times out.

**Comment by akoeplinger** [comment]
The last xharness update we got was https://github.com/dotnet/runtime/commit/c59519c0acaa6e8a87f76bf22c2eaa35414afbb1

**Comment by MattGal** [comment]
> The last xharness update we got was [dotnet/runtime@c59519c](https://github.com/dotnet/runtime/commit/c59519c0acaa6e8a87f76bf22c2eaa35414afbb1)

Do you use the Helix Xharness SDK though?  If not we'll have to discuss other ideas.

**Comment by akoeplinger** [comment]
Ah right, we're using the the XHarness SDK so this would actually be tied to the arcade version.

**Comment by greenEkatherine** [comment]
@akoeplinger could you please confirm if the issue was resolved?

**Comment by akoeplinger** [comment]
Yep.
