### ISSUE TITLE
Simulator installation fails to download the `.dmg`

### ISSUE THREAD

**Issue by premun** [dotnet/xharness#631]
```
info: Downloading 'https://devimages-cdn.apple.com/downloads/xcode/simulators/com.apple.pkg.iPhoneSimulatorSDK14_4-14.4.1.1611903691.dmg' to '/var/folders/8d/4hjmcr2x34dcmjft1gp7vjfr0000gn/T/simulator-installer/com.apple.pkg.iPhoneSimulatorSDK14_4-14.4.1.1611903691.dmg' (size: 5000672618 bytes = 4,769.01 MB)...

fail: Failed to install 'iOS 14.4 Simulator':
    System.Net.Http.HttpRequestException: Cannot write more bytes to the buffer than the configured maximum buffer size: 2147483647.
        at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken) in System.Net.Http.dll:token 0x6000280+0x17f
        at Microsoft.DotNet.XHarness.CLI.Commands.Apple.Simulators.InstallCommand.Install(Simulator simulator) in /_/src/Microsoft.DotNet.XHarness.CLI/Commands/Apple/Simulators/InstallCommand.cs:line 149
        at Microsoft.DotNet.XHarness.CLI.Commands.Apple.Simulators.InstallCommand.InvokeInternal(ILogger logger) in /_/src/Microsoft.DotNet.XHarness.CLI/Commands/Apple/Simulators/InstallCommand.cs:line 101
dbug: Skipping 'com.apple.pkg.AppleTVSimulatorSDK14_4'

XHarness exit code: 71 (GENERAL_FAILURE)
```

We probably need retries? Or download large files like this more cautiously?

**Comment by premun** [comment]
Apparently the simulator installer also stopped working for Xcode 13 beta 1

**Comment by premun** [comment]
Closing as I haven't seen it any more, might have been apple redeploying their services

**Comment by premun** [comment]
I see this on Xcode 12.4:

```
XHarness command issued: apple simulators install ios-simulator-64_13.4
info: File '/var/folders/t7/vdyhybv55ks5z6hft_zl9cww0000gp/T/simulator-installer/index-12.4.0-2F1A5FFF-BFEB-4498-B2AC-1296A7454F81.dvtdownloadableindex' already exists, skipped download
info: The simulator 'iOS 13.4 Simulator' is missing and will be installed
info: Installing 'iOS 13.4 Simulator' (13.4.1.1586370836)...
info: Downloading 'https://devimages-cdn.apple.com/downloads/xcode/simulators/com.apple.pkg.iPhoneSimulatorSDK13_4-13.4.1.1586370836.dmg' to '/var/folders/t7/vdyhybv55ks5z6hft_zl9cww0000gp/T/simulator-installer/com.apple.pkg.iPhoneSimulatorSDK13_4-13.4.1.1586370836.dmg' (size: 3358930279 bytes = 3,203.33 MB)...
fail: Failed to install 'iOS 13.4 Simulator':
      System.Net.Http.HttpRequestException: Cannot write more bytes to the buffer than the configured maximum buffer size: 2147483647.
         at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken) in System.Net.Http.dll:token 0x6000278+0x17f
         at Microsoft.DotNet.XHarness.CLI.Commands.Apple.Simulators.InstallCommand.Install(Simulator simulator) in /Users/prvysoky/Documents/xharness/src/Microsoft.DotNet.XHarness.CLI/Commands/Apple/Simulators/InstallCommand.cs:line 148
         at Microsoft.DotNet.XHarness.CLI.Commands.Apple.Simulators.InstallCommand.InvokeInternal(ILogger logger) in /Users/prvysoky/Documents/xharness/src/Microsoft.DotNet.XHarness.CLI/Commands/Apple/Simulators/InstallCommand.cs:line 100
XHarness exit code: 71 (GENERAL_FAILURE)
```
