### ISSUE TITLE
Runtime tests have issues finding the testing app on Android x64

### ISSUE THREAD

**Issue by VincentBu** [dotnet/xharness#672]
Run: [runtime 20210526.87](https://dev.azure.com/dnceng/public/_build/results?buildId=1158368&view=ms.vss-test-web.build-test-results-tab&runId=34967404&resultId=100881&paneView=debug)

Failed tests:
```
Mono Android x64 Release @ Ubuntu.1804.Amd64.Android.Open
- JIT/Methodical/*

Also failed in :

Mono Android x64 Release @ Ubuntu.1804.Amd64.Android.Open
- JIT/Regression/JitBlue/DevDiv_461649/DevDiv_461649/DevDiv_461649.sh
- Interop/StructMarshalling/ReversePInvoke/MarshalSeqStruct/DelegatePInvoke/DelegatePInvokeTest/DelegatePInvokeTest.sh
- GC/Scenarios/Dynamo/dynamo/dynamo.sh

```
**One of Error messages:**
```
Return code:      78
Raw output file:      /datadisks/disk1/work/A0E608D3/w/B0710944/e/JIT/Methodical/Reports/JIT.Methodical/VT/callconv/_il_reljumper4/_il_reljumper4.output.txt
Raw output:
BEGIN EXECUTION
XHarness command issued: android test --instrumentation=net.dot.MonoRunner --package-name=net.dot.JIT_Methodical --app=/datadisks/disk1/work/A0E608D3/w/B0710944/e/JIT/Methodical/JIT_Methodical.apk --output-directory=/datadisks/disk1/work/A0E608D3/w/B0710944/e/JIT/Methodical/VT/callconv/_il_reljumper4 --arg=entrypoint:libname=_il_reljumper4.dll --expected-exit-code=100 -v
[23:00:51] dbug: Android Test command called: App = /datadisks/disk1/work/A0E608D3/w/B0710944/e/JIT/Methodical/JIT_Methodical.apk
Instrumentation Name = net.dot.MonoRunner
[23:00:51] dbug: Output Directory:/datadisks/disk1/work/A0E608D3/w/B0710944/e/JIT/Methodical/VT/callconv/_il_reljumper4
Timeout = 900 seconds.
[23:00:51] dbug: Arguments to instrumentation:
[23:00:51] dbug: ADBRunner using ADB.exe supplied from /datadisks/disk1/work/A0E608D3/p/microsoft.dotnet.xharness.cli/1.0.0-prerelease.21271.1/tools/net6.0/any/../../../runtimes/any/native/adb/linux/adb
[23:00:51] dbug: Full resolved path:'/datadisks/disk1/work/A0E608D3/p/microsoft.dotnet.xharness.cli/1.0.0-prerelease.21271.1/runtimes/any/native/adb/linux/adb'
[23:00:51] info: Will attempt to run device on detected architecture: 'x86_64'
[23:00:51] dbug: Executing command: '/datadisks/disk1/work/A0E608D3/p/microsoft.dotnet.xharness.cli/1.0.0-prerelease.21271.1/runtimes/any/native/adb/linux/adb  start-server'
[23:00:51] dbug:
[23:00:51] dbug: Executing command: '/datadisks/disk1/work/A0E608D3/p/microsoft.dotnet.xharness.cli/1.0.0-prerelease.21271.1/runtimes/any/native/adb/linux/adb  devices -l'
[23:00:51] dbug: Evaluating output line for device serial: emulator-5554          device product:sdk_phone_x86 model:Android_SDK_built_for_x86 device:generic_x86 transport_id:1
[23:00:51] dbug: Executing command: '/datadisks/disk1/work/A0E608D3/p/microsoft.dotnet.xharness.cli/1.0.0-prerelease.21271.1/runtimes/any/native/adb/linux/adb  -s emulator-5554 shell getprop ro.product.cpu.abilist'
[23:00:51] dbug: Evaluating output line for device serial: emulator-5556          device product:sdk_phone_x86_64 model:Android_SDK_built_for_x86_64 device:generic_x86_64 transport_id:2
[23:00:51] dbug: Executing command: '/datadisks/disk1/work/A0E608D3/p/microsoft.dotnet.xharness.cli/1.0.0-prerelease.21271.1/runtimes/any/native/adb/linux/adb  -s emulator-5556 shell getprop ro.product.cpu.abilist'
[23:00:51] dbug: Using first-found compatible device of 1 total- serial: 'emulator-5556' - architecture: x86_64,x86
[23:00:51] info: Active Android device set to serial 'emulator-5556'
[23:00:51] info: Waiting for device to be available (max 5 minutes)
[23:00:51] dbug: Executing command: '/datadisks/disk1/work/A0E608D3/p/microsoft.dotnet.xharness.cli/1.0.0-prerelease.21271.1/runtimes/any/native/adb/linux/adb -s emulator-5556 wait-for-device'
[23:00:51] dbug:
[23:00:51] dbug: Executing command: '/datadisks/disk1/work/A0E608D3/p/microsoft.dotnet.xharness.cli/1.0.0-prerelease.21271.1/runtimes/any/native/adb/linux/adb -s emulator-5556 shell getprop sys.boot_completed'
[23:00:51] dbug: Waited 0.0216012 seconds for device for sys.boot_completed to be 1.
[23:00:51] dbug: Executing command: '/datadisks/disk1/work/A0E608D3/p/microsoft.dotnet.xharness.cli/1.0.0-prerelease.21271.1/runtimes/any/native/adb/linux/adb -s emulator-5556 version'
[23:00:51] dbug: Working with Android Debug Bridge version 1.0.41
Version 29.0.6-6198805
Installed as /datadisks/disk1/work/A0E608D3/p/microsoft.dotnet.xharness.cli/1.0.0-prerelease.21271.1/runtimes/any/native/adb/linux/adb

[23:00:51] info: Attempting to remove apk 'net.dot.JIT_Methodical':
[23:00:51] dbug: Executing command: '/datadisks/disk1/work/A0E608D3/p/microsoft.dotnet.xharness.cli/1.0.0-prerelease.21271.1/runtimes/a


Stack trace
   at JIT_Methodical._VT_callconv__il_reljumper4__il_reljumper4_._VT_callconv__il_reljumper4__il_reljumper4_sh()
```

**Comment by premun** [comment]
Quick glance it seems like the installation of the app failed because there was no space on the device so probably the runtime tests should fail there and not try further?

**JIT_jit64_install.output.txt**
```
[23:48:10] fail: Error:
                 Exit code: 1
                 Standard Output:
                 Performing Streamed Install
                 
                 Standard Error:
                 adb: failed to install /datadisks/disk1/work/A9CD0924/w/AF4909B5/e/JIT/jit64/JIT_jit64.apk: 
                 Exception occurred while executing:
                 android.os.ParcelableException: java.io.IOException: Requested internal only, but not enough space
                 	at android.util.ExceptionUtils.wrap(ExceptionUtils.java:34)
                 	at com.android.server.pm.PackageInstallerService.createSession(PackageInstallerService.java:467)
                 	at com.android.server.pm.PackageManagerShellCommand.doCreateSession(PackageManagerShellCommand.java:2700)
                 	at com.android.server.pm.PackageManagerShellCommand.runInstall(PackageManagerShellCommand.java:1061)
                 	at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:169)
                 	at android.os.ShellCommand.exec(ShellCommand.java:104)
                 	at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:21742)
                 	at android.os.Binder.shellCommand(Binder.java:881)
                 	at android.os.Binder.onTransact(Binder.java:765)
                 	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:4860)
                 	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:4016)
                 	at android.os.Binder.execTransactInternal(Binder.java:1021)
                 	at android.os.Binder.execTransact(Binder.java:994)
                 Caused by: java.io.IOException: Requested internal only, but not enough space
                 	at com.android.internal.content.PackageHelper.resolveInstallVolume(PackageHelper.java:234)
                 	at com.android.internal.content.PackageHelper.resolveInstallVolume(PackageHelper.java:150)
                 	at com.android.internal.content.PackageHelper.resolveInstallVolume(PackageHelper.java:165)
                 	at com.android.server.pm.PackageInstallerService.createSessionInternal(PackageInstallerService.java:571)
                 	at com.android.server.pm.PackageInstallerService.createSession(PackageInstallerService.java:465)
                 	... 11 more
                 
                 
[23:48:10] crit: Install failure: Test command cannot continue
[23:48:10] info: Attempting to remove apk 'net.dot.JIT_jit64': 
[23:48:10] info: APK 'net.dot.JIT_jit64' not on device.
XHarness exit code: 78 (PACKAGE_INSTALLATION_FAILURE)
```

@greenEkatherine we're tracking this somewhere already, right?

**Comment by greenEkatherine** [comment]
@premun yes, for issues with 78 exit code and message with "not enough space" either internal or external we raised the issue https://github.com/dotnet/xharness/issues/660 
Fix was rolled out yesterday so it should mitigate on new machines.

But also I see there are few logs with 85 exit codes which means we cannot find a device. I need to check it separately

**Comment by premun** [comment]
@greenEkatherine my point was that it seems like the runtime tests call the `install` command but ignore the exit code and then they proceed to call the `run` commands which then return "device not found" since there's no device with the app?

So I think the exit code can be misleading?

And we should probably stop the execution if we fail the installation?

**Comment by greenEkatherine** [comment]
ah, got it, nice catch! @premun you are right, tests failed with exit code == 85 because installation on previous step failed and we cannot find a device with app installed

It means that fix for https://github.com/dotnet/xharness/issues/660 should solve the issue from our side. @fanyang-mono could you please add a check for an exit code from `install` command and stop if it fails?

**Comment by fanyang-mono** [comment]
Yes, I will add that check.

**Comment by greenEkatherine** [comment]
Check was added and related issue was resolved, closing
