### ISSUE TITLE
Failed to find a x86_64 device on `ubuntu.1804.amd64.android.open.rt`

### ISSUE THREAD

**Issue by premun** [dotnet/xharness#689]
```
XHarness command issued: android install --package-name=net.dot.JIT_CodeGenBringUpTests --app=/datadisks/disk1/work/A23208C6/w/AE610977/e/JIT/CodeGenBringUpTests/JIT_CodeGenBringUpTests.apk --output-directory=/datadisks/disk1/work/A23208C6/w/AE610977/uploads/Reports/install
[22:38:50] info: Will attempt to run device on detected architecture: 'x86_64'
[22:38:50] fail: No devices with architecture 'x86_64' was found among attached and authorized devices.
[22:38:50] crit: Failed to find compatible device: x86_64
                 Microsoft.DotNet.XHarness.Common.CLI.NoDeviceFoundException: Failed to find compatible device: x86_64
                    at Microsoft.DotNet.XHarness.CLI.Commands.Android.AndroidInstallCommand.InvokeHelper(ILogger logger, String apkPackageName, String appPackagePath, IEnumerable`1 apkRequiredArchitecture, String deviceId, TimeSpan bootTimeoutSeconds, AdbRunner runner) in /_/src/Microsoft.DotNet.XHarness.CLI/Commands/Android/AndroidInstallCommand.cs:line 99
                    at Microsoft.DotNet.XHarness.CLI.Commands.Android.AndroidInstallCommand.InvokeInternal(ILogger logger) in /_/src/Microsoft.DotNet.XHarness.CLI/Commands/Android/AndroidInstallCommand.cs:line 63
XHarness exit code: 85 (ADB_DEVICE_ENUMERATION_FAILURE)
```

[[Full logs]](https://dev.azure.com/dnceng/public/_build/results?buildId=1296764&view=ms.vss-test-web.build-test-results-tab&runId=38239158&resultId=100003&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab)

Reported in https://github.com/dotnet/runtime/issues/57539

**Comment by greenEkatherine** [comment]
Might be related to https://github.com/dotnet/core-eng/issues/13359

**Comment by greenEkatherine** [comment]
Posted update there https://github.com/dotnet/core-eng/issues/13359#issuecomment-922764873

**Comment by greenEkatherine** [comment]
new issue to track progress about this issue https://github.com/dotnet/xharness/issues/754
