### ISSUE TITLE
[wasm] Incorrect parsing of xunit output

### ISSUE THREAD

**Issue by radical** [dotnet/xharness#816]
For `System.Text.RegularExpressions.Tests` ([build](https://dev.azure.com/dnceng/public/_build/results?buildId=1591256)):

```
[02:40:08] info: Starting:    System.Text.RegularExpressions.Tests.dll
[02:41:04] info: abc, beginning: 0, length: 5, expectedSuccess: True, expectedValue: "a\nabc")
[02:41:04] info: abc, beginning: 0, length: 5, expectedSuccess: True, expectedValue: "a\nabc")
[02:41:06] info: abc, beginning: 0, length: 5, expectedSuccess: True, expectedValue: "a\nabc")
[02:41:06] info: abc, beginning: 0, length: 5, expectedSuccess: True, expectedValue: "a\nabc")
[02:41:08] info: abc, beginning: 0, length: 5, expectedSuccess: True, expectedValue: "a\nabc")
[02:41:08] info: abc, beginning: 0, length: 5, expectedSuccess: True, expectedValue: "a\nabc")
[02:41:12] info: )])
[02:41:12] info: )])
[02:41:12] info: fghijkl)])
[02:41:12] info: 	
 )])
[02:41:12] info: )])
[02:41:12] info: )])
[02:41:12] info: fghijkl)])
[02:41:12] info: 	
 )])
[02:41:12] info: )])
[02:41:12] info: )])
[02:41:12] info: fghijkl)])
[02:41:12] info: 	
 )])
[02:42:06] info: Finished:    System.Text.RegularExpressions.Tests.dll
```

This seems to be parsing of the console messages breaking down.  Also, [here](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-64780-merge-1289e3b1d2944e9ca8/WasmTestOnBrowser-System.Text.RegularExpressions.Tests/1/console.f3b6ef0e.log?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-24T02%25253A12%25253A25Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DM97gY%25252FhA7HRuGnunRdv18SYnYCOqowG%25252FqfgRfCqgEVs%25253D), we get an exception too:

```
fail: "System.AggregateException: One or more errors occurred. ('.', hexadecimal value 0x00, is an invalid character.)
 ---> System.ArgumentException: '.', hexadecimal value 0x00, is an invalid character.
   at System.Xml.XmlUtf8RawTextWriter.InvalidXmlChar(Int32 ch, Byte* pDst, Boolean entitize) in /_/src/libraries/System.Private.Xml/src/System/Xml/Core/XmlUtf8RawTextWriter.cs:line 1475
   at System.Xml.XmlUtf8RawTextWriter.WriteAttributeTextBlock(Char* pSrc, Char* pSrcEnd) in /_/src/libraries/System.Private.Xml/src/System/Xml/Core/XmlUtf8RawTextWriter.cs:line 819
   at System.Xml.XmlUtf8RawTextWriter.WriteString(String text) in /_/src/libraries/System.Private.Xml/src/System/Xml/Core/XmlUtf8RawTextWriter.cs:line 535
   at System.Xml.XmlUtf8RawTextWriterIndent.WriteString(String text) in /_/src/libraries/System.Private.Xml/src/System/Xml/Core/XmlUtf8RawTextWriter.cs:line 1961
   at System.Xml.XmlWellFormedWriter.WriteString(String text) in /_/src/libraries/System.Private.Xml/src/System/Xml/Core/XmlWellFormedWriter.cs:line 1091
   at System.Xml.XmlWriter.WriteAttributeString(String prefix, String localName, String ns, String value) in /_/src/libraries/System.Private.Xml/src/System/Xml/Core/XmlWriter.cs:line 112
   at System.Xml.Linq.ElementWriter.WriteStartElement(XElement e) in /_/src/libraries/System.Private.Xml.Linq/src/System/Xml/Linq/XLinq.cs:line 384
   at System.Xml.Linq.ElementWriter.WriteElement(XElement e) in /_/src/libraries/System.Private.Xml.Linq/src/System/Xml/Linq/XLinq.cs:line 216
   at System.Xml.Linq.XElement.WriteTo(XmlWriter writer) in /_/src/libraries/System.Private.Xml.Linq/src/System/Xml/Linq/XElement.cs:line 1299
   at System.Xml.Linq.XElement.Save(XmlWriter writer) in /_/src/libraries/System.Private.Xml.Linq/src/System/Xml/Linq/XElement.cs:line 1162
   at System.Xml.Linq.XElement.Save(Stream stream, SaveOptions options) in /_/src/libraries/System.Private.Xml.Linq/src/System/Xml/Linq/XElement.cs:line 1062
   at System.Xml.Linq.XElement.Save(Stream stream) in /_/src/libraries/System.Private.Xml.Linq/src/System/Xml/Linq/XElement.cs:line 1044
   at Microsoft.DotNet.XHarness.TestRunners.Xunit.ThreadlessXunitTestRunner.WriteResultsToFile(TextWriter writer, XmlResultJargon jargon)
   at Microsoft.DotNet.XHarness.TestRunners.Common.ApplicationEntryPoint.WriteResults(TestRunner runner, ApplicationOptions options, LogWriter logger, TextWriter writer)
   at Microsoft.DotNet.XHarness.TestRunners.Common.ApplicationEntryPoint.InternalRunAsync(ApplicationOptions options, TextWriter loggerWriter, TextWriter resultsFile)
   at Microsoft.DotNet.XHarness.TestRunners.Common.WasmApplicationEntryPointBase.RunAsync()
   at Microsoft.DotNet.XHarness.TestRunners.Xunit.WasmApplicationEntryPoint.Run()
   at SimpleWasmTestRunner.Main(String[] args) in /_/src/libraries/Common/tests/WasmTestRunner/WasmTestRunner.cs:line 61
   --- End of inner exception stack trace ---"
```

I haven't seen this exception before though, but seems related to the message parsing issue.

cc @lewing @maraf @pavelsavara

**Comment by radical** [comment]
I'm not sure what might be causing the exception. I can't reproduce it. It seems to be failing because it hits a NUL char while writing an attribute on the starting element. The beginning of the result xml looks like (not from the failing case):

```xml
<?xml version="1.0" encoding="utf-8"?>
<assemblies>
  <assembly name="System.Text.RegularExpressions.Tests.dll" environment="32-bit .NET  [collection-per-class, non-parallel]" test-framework="xUnit.net 2.4.2.0" run-date="2022-02-07" run-time="14:23:35" total="1306" passed="1303" failed="3" skipped="0" time="6.175" errors="0">
...
```
