### ISSUE TITLE
Starting the ADB server fails

### ISSUE THREAD

**Issue by premun** [dotnet/xharness#822]
This happened on `ubuntu.1804.amd64.android.29.open`:

> [11:38:24] dbug: Executing command: '/datadisks/disk1/work/AA8509A6/p/microsoft.dotnet.xharness.cli/1.0.0-prerelease.22114.1/runtimes/any/native/adb/linux/adb start-server'
[11:38:34] dbug: 
[11:38:34] crit: Error starting ADB Server.  Std out: Std. Err: error: protocol fault (couldn't read status): Connection reset by peer
>                 
>                 System.Exception: Error starting ADB Server.  Std out: Std. Err: error: protocol fault (couldn't read status): Connection reset by peer
>                 
>                    at Microsoft.DotNet.XHarness.Android.AdbRunner.StartAdbServer() in /_/src/Microsoft.DotNet.XHarness.Android/AdbRunner.cs:line 195
>                    at Microsoft.DotNet.XHarness.CLI.Commands.Android.AndroidInstallCommand.InvokeHelper(ILogger logger, String apkPackageName, String appPackagePath, IEnumerable`1 apkRequiredArchitecture, String deviceId, TimeSpan bootTimeoutSeconds, AdbRunner runner, IDiagnosticsData diagnosticsData) in /_/src/Microsoft.DotNet.XHarness.CLI/Commands/Android/AndroidInstallCommand.cs:line 100
>                    at Microsoft.DotNet.XHarness.CLI.Commands.Android.AndroidTestCommand.InvokeInternal(ILogger logger) in /_/src/Microsoft.DotNet.XHarness.CLI/Commands/Android/AndroidTestCommand.cs:line 75
> [11:38:34] dbug: Saving diagnostics data to '/datadisks/disk1/work/AA8509A6/w/B68B0968/e/diagnostics.json'
> XHarness exit code: 71 (GENERAL_FAILURE)

[[Full logs]](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-65551-merge-4e7275bd95c44e129c/System.Xml.XPath.XmlDocument.Tests/1/console.feff1d4e.log?sv=2019-07-07&se=2022-03-13T11:21:48Z&sr=c&sp=rl&sig=iwyHFgEspCB9CAZ5gm6JCpdeub6c%2FCqcQbxATiU%2BB68%3D)

Another work item passed just 30 seconds later on the same VM so might be transient. 

We should check if we retry this in code. We should consider adding a specific exit code to ADB failures and then retrying work items for those.

**Comment by premun** [comment]
This should be hopefully fixed with the retries
