### ISSUE TITLE
xharness test failures when running WASM build tests locally

### ISSUE THREAD

**Issue by layomia** [dotnet/xharness#891]
<details>
<summary>As part of PR dotnet/runtime#65966 I'm adding a new WASM build test (click to expand)</summary>

```cs
[ConditionalTheory(typeof(BuildTestBase), nameof(IsUsingWorkloads))]
[BuildAndRun(aot: false)]
[BuildAndRun(aot: true)]
public void ProjectUsingBrowserNativeCrypto(BuildArgs buildArgs, RunHost host, string id)
{
    string projectName = $"AppUsingBrowserNativeCrypto";
    buildArgs = buildArgs with { ProjectName = projectName };
    buildArgs = ExpandBuildArgs(buildArgs);

    string programText = @"
using System;
using System.Security.Cryptography;
public class Test
{
public static int Main()
{
using (SHA256 mySHA256 = SHA256.Create())
{
    byte[] data = { (byte)'H', (byte)'e', (byte)'l', (byte)'l', (byte)'o' };
    byte[] hashed = mySHA256.ComputeHash(data);
    string asStr = string.Join(' ', hashed);
    Console.WriteLine(""Hashed: "" + asStr);
    return 0;
}
}
}";

    BuildProject(buildArgs,
                    id: id,
                    new BuildProjectOptions(
                        InitProject: () => File.WriteAllText(Path.Combine(_projectDir!, "Program.cs"), programText),
                        DotnetWasmFromRuntimePack: !buildArgs.AOT && buildArgs.Config != "Release"));

    string output = RunAndTestWasmApp(buildArgs, buildDir: _projectDir, expectedExitCode: 0,
                        test: output => {},
                        host: host, id: id);

    Assert.Contains(
        "Hashed: 24 95 141 179 34 113 254 37 245 97 166 252 147 139 46 38 67 6 236 48 78 218 81 128 7 209 118 72 38 56 25 105",
        output);

    string cryptoInitMsg = "MONO_WASM: Initializing Crypto WebWorker";
    if (host == RunHost.V8 || host == RunHost.NodeJS)
    {
        Assert.DoesNotContain(cryptoInitMsg, output);
    }
    else
    {
        Assert.Contains(cryptoInitMsg, output);
    }
}
```
</details>

I'm seeing it and other pre-existing tests fail (non-deterministically) locally (win-x64). Here's a sample log https://gist.github.com/layomia/87092f56d63ff3691e19491606b3bdd0. This is unexpected behavior from xharness per discussion with @radical.

**Comment by radical** [comment]
```
crit: System.AggregateException: One or more errors occurred. (Specified argument was out of the range of valid values.)
       ---> System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
         at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
         at System.IO.StreamWriter.WriteLine(String value)
         at Microsoft.DotNet.XHarness.CLI.Commands.Wasm.WasmTestMessagesProcessor.InvokeInternal(String message) in /_/src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/WasmTestMessagesProcessor.cs:line 129
         at Microsoft.DotNet.XHarness.CLI.Commands.Wasm.WasmTestMessagesProcessor.Invoke(String message) in /_/src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/WasmTestMessagesProcessor.cs:line 52
         at Microsoft.DotNet.XHarness.CLI.Commands.Wasm.WasmBrowserTestRunner.RunConsoleMessagesPump(WebSocket socket, TaskCompletionSource`1 tcs, CancellationToken token) in /_/src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/Browser/WasmBrowserTestRunner.cs:line 171
         at Microsoft.DotNet.XHarness.CLI.Commands.WebServer.TestWebServerStartup.<>c__DisplayClass3_0.<<Configure>b__2>d.MoveNext() in /_/src/Microsoft.DotNet.XHarness.CLI/Commands/WebServer.cs:line 163
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
         --- End of inner exception stack trace ---
         at Microsoft.DotNet.XHarness.CLI.Commands.Wasm.WasmBrowserTestRunner.RunTestsWithWebDriver(DriverService driverService, IWebDriver driver) in /_/src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/Browser/WasmBrowserTestRunner.cs:line 128
         at Microsoft.DotNet.XHarness.CLI.Commands.Wasm.WasmTestBrowserCommand.InvokeInternal(ILogger logger) in /_/src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/Browser/WasmTestBrowserCommand.cs:line 77
         at Microsoft.DotNet.XHarness.CLI.Commands.XHarnessCommand`1.Invoke(IEnumerable`1 arguments) in /_/src/Microsoft.DotNet.XHarness.CLI/Commands/XHarnessCommand.cs:line 145
XHarness exit code: 71 (GENERAL_FAILURE)
```

This is likely being caused by `Microsoft.DotNet.XHarness.CLI.Commands.Wasm.WasmTestMessagesProcessor.Invoke(String message)` being called from two threads at the same time.
